#!/usr/bin/env python3
from workflow.workflow import Project
import argparse
import logging
import sys


def _check_python_version_compatible():
    if sys.version_info < (3, 5):
        print('This application requires Python 3.5 or greater.\n',
              'Version',
              str(sys.version_info),
              'detected.'
              )
        sys.exit(1)


def _check_imod_installed():
    from shutil import which
    if which('imod') is None:
        print('This application requires imod be installed. Exiting')
        sys.exit(1)


def _check_scipion_installed():
    from shutil import which
    if which('scipion') is None:
        print('This application requires scipion be installed. Exiting')
        sys.exit(1)


def _parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--project',
                        required=True,
                        help='Project identifier')
    parser.add_argument('--pattern',
                        required=True,
                        help='A globbing pattern to match files for import and\
                        processing')
    parser.add_argument('--frames',
                        required=False,
                        type=int,
                        help='Set to the number of frames that will need to be\
                        stacked per-movie. Defaults to 1 (already stacked)')
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    args = _parse_arguments()
    logging.basicConfig(level=logging.INFO)
    _check_python_version_compatible()
    _check_scipion_installed()
    _check_imod_installed()
    project = Project(project=args.project,
                      pattern=args.pattern,
                      frames=args.frames or 1)
    project.start()
