#!/usr/bin/env python3
from workflow.workflow import Project
from workflow.config import Config, ScipionTemplate
import argparse
import logging
import os
import pathlib
import sys


def _check_applications():
    if sys.version_info < (3, 5):
        msg = ''.join(
            ('This application requires Python 3.5 or greater.\n',
             'Version',
             str(sys.version_info),
             'detected.'))
        sys.exit(msg)
    from shutil import which
    if which('lbzip2') is None:
        sys.exit('This application requires lbzip2 be installed. Exiting')
    if which('scipion') is None:
        sys.exit('This application requires scipion be installed. Exiting')
    if which('imod') is None:
        sys.exit('This application requires imod be installed. Exiting')
    try:
        import transitions  # noqa: F401
    except ImportError:
        sys.exit('The python module "transitions" is not installed. Exiting')


def _parse_arguments():
    parser = argparse.ArgumentParser()
    parser.add_argument('--dst-directory', '-d',
                        required=False,
                        type=str,
                        help='Destination directory for Globus transfer.')
    parser.add_argument('--no-scipion',
                        required=False,
                        action='store_true',
                        help='Disable scipion startup. Useful for restarting\
                        transfers if scipion is already running or is being\
                        started separately.')
    parser.add_argument('-v', '--debug', '--verbosity',
                        required=False,
                        type=str,
                        help='Provide a verbosity level like INFO or DEBUG\n\
                        Defaults to the equivalent of --debug INFO')
    args = parser.parse_args()
    return args


if __name__ == '__main__':
    args = _parse_arguments()
    _check_applications()
    config = Config()
    config.load(pathlib.Path('config/default/base_system_config.json'))
    config.prompt_user_configs()
    config.prompt_for_unset_values()
    config.validate_all()
    config.save(
        path=pathlib.Path(config.config_options.get('run_config_directory'),
                          config.config_options['project_name'] + '.json'))
    template = ScipionTemplate(config)
    template.generate_config()
    logging.basicConfig(
        level=getattr(logging, args.debug) if args.debug else logging.INFO,
        filename=args.log_file or '/mnt/nas/pipeline/'+project_name+'.log')
    logging.getLogger('transitions').setLevel(logging.WARNING)
    logger = logging.getLogger(__name__)
    if os.fork():
        sys.exit()
    project = Project(config)
    logger.info('Parameters')
    for val in vars(config.config_options):
        logger.info(': '.join((val, str(getattr(config.config_options, val)))))
    project.start()
